version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: beavercoredb
      POSTGRES_USER: beaveruser
      POSTGRES_PASSWORD: beaverpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: