spring:
  application:
    name: beaver-core-local

  datasource:
    url: jdbc:postgresql://localhost:5432/beavercoredb
    username: beaveruser
    password: beaverpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000   # 15 minutes
  refresh-token-expiration: 86400000 # 24 hours