spring:
  application:
    name: beaver-core-local

  datasource:
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: defaultSecretKeyThatIsLongEnoughForHS256Algorithm
  access-token-expiration: 900000   # 15 minutes
  refresh-token-expiration: 86400000 # 24 hours