spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

#  security:
#    user:
#      name: connor
#      password: password

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
